"""Centralised artifact path management for the PRS pipeline.

Every analysis module (inference, validation, interpretability, plots)
previously constructed the same trace/scaler/mappings/dataset paths with
identical f-strings.  ``ModelPaths`` provides a single source of truth
so that renaming an artifact only requires editing one property.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from config import MODEL_TRACES_DIR, PROCESSED_DATA_DIR, TABLES_DIR


@dataclass(frozen=True)
class ModelPaths:
    """File-system paths for all artifacts generated by a single holdout run."""

    holdout: str

    @property
    def trace(self) -> Path:
        return MODEL_TRACES_DIR / f"pooled_trace_{self.holdout}.nc"

    @property
    def scaler(self) -> Path:
        return MODEL_TRACES_DIR / f"pooled_scaler_{self.holdout}.pkl"

    @property
    def mappings(self) -> Path:
        return MODEL_TRACES_DIR / f"pooled_mappings_{self.holdout}.pkl"

    @property
    def training_dataset(self) -> Path:
        return PROCESSED_DATA_DIR / f"all_pressure_dataset_{self.holdout}.parquet"

    @property
    def holdout_dataset(self) -> Path:
        return PROCESSED_DATA_DIR / f"holdout_pressure_dataset_{self.holdout}.parquet"

    @property
    def leaderboard(self) -> Path:
        return TABLES_DIR / f"prs_leaderboard_{self.holdout}.csv"

    @property
    def holdout_metrics(self) -> Path:
        return TABLES_DIR / f"holdout_metrics_{self.holdout}.csv"

    @property
    def holdout_correlation(self) -> Path:
        return TABLES_DIR / f"holdout_correlation_data_{self.holdout}.csv"

    @property
    def calibration_curve(self) -> Path:
        return TABLES_DIR / f"calibration_curve_{self.holdout}.csv"


def require_paths(*paths: Path) -> None:
    """Raise ``FileNotFoundError`` with an actionable message listing every missing
    artifact, so the user knows exactly which pipeline step to run first."""
    missing = [str(p) for p in paths if not p.exists()]
    if missing:
        raise FileNotFoundError(
            "Required model artifact(s) missing — run the pipeline from data "
            "build through model fitting first.\n  Missing: "
            + "\n  Missing: ".join(missing)
        )
